SELECT TO_CHAR((SYSDATE - TO_DATE(B.LAST_LOAD_TIME, 'yyyy-mm-dd/hh24:mi:ss')) * 24 * 60,'FM999,990.90') MINUTES,
       A.PROGRAM,
       A.MACHINE,
       A.OSUSER,
      -- B.SQL_FULLTEXT,
      TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 1, 2000)) SQL_TEXT1,
       
       /*TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 4001, 4000)) SQL_FULL_TEXT2,
       TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 8001, 4000)) SQL_FULL_TEXT3,
       TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 12001, 4000)) SQL_FULL_TEXT4,
       TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 16001, 4000)) SQL_FULL_TEXT5,
       TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 20001, 4000)) SQL_FULL_TEXT6,
       TO_CHAR(SUBSTR(B.SQL_FULLTEXT, 24001, 4000)) SQL_FULL_TEXT7,*/
       B.SQL_FULLTEXT SQL_FULL,
       A.EVENT,
       --A.BLOCKING_INSTANCE,
       A.BLOCKING_SESSION BK_SS,
       S_BK.EVENT BK_EVENT,
       A.P1,
       A.P2,
       A.P3,
       A.SID,
       A.SERIAL#,
       A.SQL_ID,
       A.SQL_CHILD_NUMBER,
       A.USERNAME,
       A.STATUS
      -- 'alter system kill session ''' || A.SID || ',' || A.SERIAL# || ''';' KILL_SESSION

  FROM V$SESSION A
  LEFT JOIN V$SQL B
    ON A.SQL_ADDRESS = B.ADDRESS
   AND A.SQL_HASH_VALUE = B.HASH_VALUE
   AND A.SQL_CHILD_NUMBER = B.CHILD_NUMBER
   --AND B.SQL_TEXT NOT LIKE
   --    'SELECT TO_CHAR((SYSDATE - TO_DATE(B.LAST_LOAD_TIME%'

  LEFT JOIN V$SESSION S_BK
    ON A.BLOCKING_SESSION = S_BK.SID

WHERE A.STATUS = 'ACTIVE' --'INACTIVE'
   AND B.SQL_TEXT IS NOT NULL
--AND A.USERNAME IN ('ADAM_STG','ADAM_TGT') 
--AND UPPER(SQL_TEXT) LIKE 'UPDATE%' 

--AND  A.SID=2840
--AND UPPER(B.SQL_TEXT) LIKE 'UPDATE %ADAM_INDIVIDUAL_HISTORY%'
ORDER BY A.OSUSER, B.LAST_LOAD_TIME DESC;--, B.SQL_TEXT, A.SID;
